### ISSUE TITLE
Emit "internal" key in JSON output

### ISSUE THREAD

**Issue by ilikebits** [KyleBanks/depth#13]
It would be excellent if the JSON output included a boolean called `internal` that indicated whether a package is from the standard library.

**Comment by KyleBanks** [comment]
Yeah this is a good idea, should be an easy implementation as well. I'd be happy to provide assistance if you (or anyone else) wants to add it!

**Comment by KyleBanks** [comment]
All thats needed is a tweak to the `json` annotation here on the `Pkg` struct here: https://github.com/KyleBanks/depth/blob/master/pkg.go#L16

And a few updates to fix what will be failing test cases.
