### ISSUE TITLE
I had the same problem, but it worked when it called it from the `cmd` folder (where `main.go` is)

### ISSUE THREAD

**Issue by virak-panha** [KyleBanks/depth#19]
I had the same problem, but it worked when it called it from the `cmd` folder (where `main.go` is)

_Originally posted by @ghohmann-asapp in https://github.com/KyleBanks/depth/issues/18#issuecomment-540127086_

**Comment by KyleBanks** [comment]
Closing as a duplicate of https://github.com/KyleBanks/depth/issues/18
