### ISSUE TITLE
Output a summary after tree

### ISSUE THREAD

**Issue by KyleBanks** [KyleBanks/depth#4]
It would be nice to have a summary printed below the tree, for example:

```
12 dependencies (8 internal, 4 external).
```

If the `-test` flag is set it would also show test-only dependencies:

```
15 dependencies (8 internal, 4 external, 3 testing).
```

**Comment by dgarrick** [comment]
I'm interested in taking a crack at this. I have a clarification question, however. Should we consider the same dependency multiple times, if it appears multiple times? Or only count unique dependencies?

For example, this is what I'm picturing:
```./depth github.com/KyleBanks/depth/cmd/depth               depth_summary 
github.com/KyleBanks/depth/cmd/depth
  ├ encoding/json
  ├ flag
  ├ fmt
  ├ io
  ├ os
  ├ strings
  └ github.com/KyleBanks/depth
    ├ bytes
    ├ errors
    ├ go/build
    ├ os
    ├ path
    ├ sort
    └ strings
14 dependencies (13 internal, 1 external, 0 testing)

strings, os, etc, occur multiple times in internal packages to depth, but we count each occurrence as a separate dependency.

**Comment by KyleBanks** [comment]
@dgarrick my first thought was to only count unique dependencies, so in the example above you'd get 11 internal, 1 external. In bigger projects the numbers would probably grow way too fast otherwise as common dependencies like errors and strings get added over and over

**Comment by dgarrick** [comment]
@KyleBanks that makes sense. I should be able to get a PR for this by the weekend, time permitting.

**Comment by dgarrick** [comment]
Time did not permit (I'm currently in the process of changing jobs/apartments/cities, so things are a little more hectic than I anticipated.)

Overall, everything is almost done and I'm wrapping up the necessary test code changes.

I have run into an issue, however. `cmd/depth/depth.go` imports `github.com/KyleBanks/depth`. Therefore, any local changes I make to files in the `depth` package are not seen by the `cmd/depth` package. I can, of course, fix it locally by just replacing the GitHub import with a plain `depth` import, but obviously that's not a great solution permanently.

**Comment by KyleBanks** [comment]
Hey @dgarrick, no worries you sound pretty busy!

Regarding the import issue, it should work if you checkout the project at `$GOPATH/src/github.com/KyleBanks/depth` and make your changes there. You can then point that directory to your fork on GitHub by changing the `remote` to  your fork, see: http://code.openark.org/blog/development/forking-golang-repositories-on-github-and-managing-the-import-path
